server:
  port: 9002

spring:
  application:
    name: stock-service
  kafka:
    topic:
      name: order-topic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-events-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: com.cogent.stock_service.payload.OrderEvent
#      spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      spring.kafka.consumer.value-deserializer.delegate: org.springframework.kafka.support.serializer.JsonDeserializer
#      spring.kafka.consumer.error-handler: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG